module.exports = {
  'cereals': [
    {'id': 'apple-cinnamon-cheerios', 'label': 'Apple Cinnamon Cheerios'},
    {'id': 'cinnamon-toast-crunch', 'label': 'Cinnamon Toast Crunch'},
    {'id': 'yogurt-burst-cheerios', 'label': 'Yogurt Burst Cheerios'},
    {'id': 'multi-grain-cheerios', 'label': 'Multi-Grain Cheerios'},
    {'id': 'honey-nut-cheerios', 'label': 'Honey Nut Cheerios'},
    {'id': 'chocolate-cheerios', 'label': 'Chocolate Cheerios'},
    {'id': 'frosted-cheerios', 'label': 'Frosted Cheerios'},
    {'id': 'berry-berry-kix', 'label': 'Berry Berry Kix'},
    {'id': 'golden-grahams', 'label': 'Golden Grahams'},
    {'id': 'fruity-pebbles', 'label': 'Fruity Pebbles'},
    {'id': 'frosted-flakes', 'label': 'Frosted Flakes'},
    {'id': 'count-chocula', 'label': 'Count Chocula'},
    {'id': 'rice-krispies', 'label': 'Rice Krispies'},
    {'id': 'cinnamon-life', 'label': 'Cinnamon Life'},
    {'id': 'cocoa-pebbles', 'label': 'Cocoa Pebbles'},
    {'id': 'reeses-puffs', 'label': "Reese's Puffs"},
    {'id': 'cinnamon-chex', 'label': 'Cinnamon Chex'},
    {'id': 'waffle-crisp', 'label': 'Waffle Crisp'},
    {'id': 'cookie-crisp', 'label': 'Cookie Crisp'},
    {'id': 'lucky-charms', 'label': 'Lucky Charms'},
    {'id': 'golden-crisp', 'label': 'Golden Crisp'},
    {'id': 'capn-crunch', 'label': "Cap'n Crunch"},
    {'id': 'honey-smacks', 'label': 'Honey Smacks'},
    {'id': 'mini-wheats', 'label': 'Mini-Wheats'},
    {'id': 'cocoa-puffs', 'label': 'Cocoa Puffs'},
    {'id': 'froot-loops', 'label': 'Froot Loops'},
    {'id': 'raisin-bran', 'label': 'Raisin Bran'},
    {'id': 'apple-jacks', 'label': 'Apple Jacks'},
    {'id': 'wheat-chex', 'label': 'Wheat Chex'},
    {'id': 'alpha-bits', 'label': 'Alpha-Bits'},
    {'id': 'grape-nuts', 'label': 'Grape-Nuts'},
    {'id': 'corn-chex', 'label': 'Corn Chex'},
    {'id': 'boo-berry', 'label': 'Boo Berry'},
    {'id': 'special-k', 'label': 'Special K'},
    {'id': 'corn-pops', 'label': 'Corn Pops'},
    {'id': 'rice-chex', 'label': 'Rice Chex'},
    {'id': 'cheerios', 'label': 'Cheerios'},
    {'id': 'all-bran', 'label': 'All-Bran'},
    {'id': 'wheaties', 'label': 'Wheaties'},
    {'id': 'crispix', 'label': 'Crispix'},
    {'id': 'smorz', 'label': 'Smorz'},
    {'id': 'krave', 'label': 'Krave'},
    {'id': 'ohs', 'label': "Oh's"},
    {'id': 'trix', 'label': 'Trix'},
    {'id': 'kix', 'label': 'Kix'}
  ]
}
